### ISSUE TITLE
binary files

### ISSUE THREAD

**Issue by krya** [jisaacks/GitGutter#189]
if you try to open a binary file gitgutter raises an exception

``` python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./git_gutter.py", line 45, in run
  File "./view_collection.py", line 51, in diff
  File "./git_gutter_handler.py", line 156, in diff
LookupError: unknown encoding: Hexadecimal
```

sublime 2 on linux here.

**Comment by KevinLi** [comment]
ST3 still returns "Hexadecimal" in the hexadecimal view.
I've just made a pull request that should fix this.

**Comment by rchl** [comment]
@KevinLi Can't see your pull request :)

**Comment by KevinLi** [comment]
Me neither!

**Comment by KevinLi** [comment]
Me neither! I have no idea what's going on!
It's been nearly two years; does the bug still exist?

**Comment by rchl** [comment]
I think it still exists looking at the code. There is no rewriting of encoding from 'Hexadecimal' to 'hex'.

**Comment by jisaacks** [comment]
> Me neither! I have no idea what's going on!

Probably, you deleted the repo from your own account, which the fork was based on. So the fork went away?
