### ISSUE TITLE
Problem with smudge/clean filters

### ISSUE THREAD

**Issue by fd** [jisaacks/GitGutter#74]
Smudge/clean filters are not applied by `git show` which causes GitGutter to detect ghost-changes.

**Comment by kofalt** [comment]
Hello @jisaacks!  I just ran into this today and I can help lend some context.

Git filters allow you to modify files when checking out or committing. You can do a couple cool things with this: store & version an encrypted file alongside your normal source code, for example. I think the Windows Git client uses filters to solve compatibility problems with line endings as well.

Docs are [here](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#Keyword-Expansion) but the pictures are pretty great:

![smudge](https://cloud.githubusercontent.com/assets/265071/13125849/49e1332a-d58d-11e5-975f-c3f2ec840eb0.png)

![clean](https://cloud.githubusercontent.com/assets/265071/13125853/4b76f116-d58d-11e5-9e4f-4c79ebc63092.png)

Here's a popular python library, edited locally as tabs, without messing up the diff:

```bash
# Grab an example repo
git clone https://github.com/kennethreitz/requests.git && cd requests

# Create a filter called "tabspace"
git config filter.tabspace.smudge 'unexpand --tabs=4 --first-only'
git config filter.tabspace.clean  'expand   --tabs=4 --initial'

# Tell git to run the filter on all python files
echo '*.py  filter=tabspace' >> .git/info/attributes

# Bit silly: delete all tracked files & checkout again to trigger the filter
git rm -rf -q .
git reset -q .
git checkout .

# Have a look!
sublime_text requests/cookies.py
```

You'll see that the `smudge` filter has been applied and the file is indented with tabs, unlike its [upstream variant](https://github.com/kennethreitz/requests/blob/master/requests/cookies.py). Meanwhile, `git diff` is empty, because the `clean` filter applies before diffing or comitting.

You'll also see that GitGutter thinks each line changed by a filter has a diff status:

![gutter](https://cloud.githubusercontent.com/assets/265071/13126704/275ac8e4-d591-11e5-8c23-57edf4f5c7c9.png)

I think this is what @fd was getting at - that GitGutter's method for checking the diff ([here?](https://github.com/jisaacks/GitGutter/blob/6f3d9783aec01ac5efc8456bfe78c5fcdc6dec0c/git_gutter_handler.py#L154)) doesn't account for git filters, which leads to erroneous reporting.

I'm not sure of the best approach for a fix - all the information is stored in the standard git config files, so it's possible to smudge manually, but ideally there's a way to ask git to handle it for you.

**Comment by jisaacks** [comment]
@kofalt that makes sense. Thanks for explaining. You are correct that is where the diff is happening but you may not have noticed that its not actually diff'ing the file or the repo. There is a function called [`update_buf_file`](https://github.com/jisaacks/GitGutter/blob/master/git_gutter_handler.py#L64) that creates a temp file with the contents of what is in sublime text. There is another function called [`update_git_file`](https://github.com/jisaacks/GitGutter/blob/master/git_gutter_handler.py#L89) that creates a temp file with the contents of what git has for that file. Then it asks git to diff those 2 temp files. So I am wondering if maybe in the `update_git_file` function, it can ask for the contents to be smudged, since the contents of the sublime file are already smudged (if I am understanding correctly.)

**Comment by kofalt** [comment]
That sounds right to me.
Am I reading `update_git_file` correctly in that it is basically running `git show HEAD:[file]`?

I was surprised to find no obvious ways to make `git show` apply a smudge filter. Considering asking the git maintainers for a flag. I did find two cheeky ways to apply filters without messing with the repo:

```bash
# Not smudged
$ git show HEAD:requests/cookies.py
...
    import threading

# Smudged! (renders in github as spaces; works IRL)
$ git archive HEAD requests/cookies.py | tar x requests/cookies.py -O
...
	import threading

# Also smudged! Doesn't use archives, but does touch disk
$ mkdir -p ../oy
$ git --work-tree=../oy checkout requests/cookies.py
$ cat ../oy/requests/cookies.py
...
	import threading
```

If you've got a more clever approach, that'd clearly be preferable :)

**Comment by kofalt** [comment]
Hmm. I just noticed that after running `git show` you're writing the result to disk anyway for git to read. Given that, the second option (using `checkout` with a work-tree option) might be a valid drop-in replacement.

**Comment by deathaxe** [comment]
I prepared a simple fix for this issue locally by replacing the `git show` command by `git archive`. 

It depends on the fix for Issue #340 which is not yet published due to pending PRs.

**Comment by kofalt** [comment]
That's awesome :+1: 

I still use git filters, so if you show me a way to test a new version of the plugin I will gladly do so!

**Comment by deathaxe** [comment]
@kofalt: You could checkout the commits from my PR and help reviewing and bug hunting.

**Comment by kofalt** [comment]
I've got good news & bad news :smile: 

Using my example above, on the tip of GitGutter master:

![](https://cloud.githubusercontent.com/assets/265071/22899154/787e9478-f1ef-11e6-819a-11af98b6e1ba.png)

Using `173e502`, the current tip of #372:

![](https://cloud.githubusercontent.com/assets/265071/22899236/c07666ca-f1ef-11e6-9f96-41e2d9bc0268.png)

So that works!

The bad news is that it looks like it's easily confused by symlinks. 
So if you use my example above, but:

```bash
# Leave the directory we cloned into
cd ..

# Alias the directory
ln -s requests/ link

# Have a look via the symlink 
sublime_text link/requests/cookies.py
```

You'll see this:

![](https://cloud.githubusercontent.com/assets/265071/22899333/1b9d5176-f1f0-11e6-8f4c-0c9bee528ff1.png)

It looks like I can reproduce that error without filters though. If you like I can file that as a separate ticket!

**Comment by deathaxe** [comment]
Good news for the bad news: I found the reason. This is not related to the smudge stuff but a more common issue. Will fix it.

**Comment by deathaxe** [comment]
Pushed the fix to master and the PR branch. Should work now.

**Comment by zertrin** [comment]
Hi, I just found this issue because after setting up a .gitattribute filter to strip output data and metadata from ipython notebooks (https://github.com/kynan/nbstripout) and making sure that it is working in git bash when diffing, adding and commiting, GitGutter still shows me differences for these chunks (see screenshot below).

![gitgutter_iss74_filter](https://cloud.githubusercontent.com/assets/1447163/23883728/ed690c08-08a3-11e7-926c-4a1764173b6e.png)

`git status` and `git diff` correctly report no changes to that file (even if the working copy differs from the index).

I'm using GitGutter v1.5.0 with ST3

My .gitattribute file contains:

    *.ipynb filter=nbstripout

and the filter is set up as the following:

    filter.nbstripout.clean="c:/users/xxxxxxxxxx/appdata/local/continuum/anaconda3/python.exe" "c:/users/xxxxxxxxxx/appdata/local/continuum/anaconda3/lib/site-packages/nbstripout.py"
    filter.nbstripout.smudge=cat
    filter.nbstripout.required=true

I am suspecting that the problem comes from the fact that the smudge filter in my case would result in a different file than the one currently in the working copy (the commited file contains no outputs, while the one in the working copy still has the outputs that were subsequently filtered by the clean filter while adding and committing).

So I guess my question is: what files does GitGutter compares exactly to make a decision? Does GitGutter uses the working copy file at all? IMHO it shouldn't use the one in the working copy (that may not have been smudged yet). The comparison should be done between the "working copy file after cleaning" and the file in the index.

However that raises the question of how can gitgutter associate the lines between the "working copy" and the "working copy after applying the clean filter" in order to show the diff on the "working copy" file...

.... the more I write this comment, the more I see that this isn't easily solvable, and that assuming that the working copy file has to be already smudged may be the only solution.

**Comment by deathaxe** [comment]
### How GitGutter works

GitGutter basically creates 2 files in your temp folder (git_gutter_...) which are compared against each other using `git diff --no-index ... <file1> <file2>`.

The `<file1>` contains a copy of Sublime Text's `view`.
The `<file2>` contains the unzipped content of `git archive --format=zip <hash> <file_name>`

The `<hash>` is the current commit hash of your compare target (HEAD, branch, tag). `<file2>` is updated only, if this `<hash>` changes. The `<file_name>` is the relative path of the file within the index.

As descriped in some posts above smudge filters are applied to `<file2>` by `git archive`. 

### Conclusion

This means you can use smudge filters, which will manipulate the file when it is checked out, but you can't use smudge filters, which manipulate the working file before commit.

There is no way to apply any smudge filters on `<file1>`!


### Diff

As you stated correctly, we can't call `git diff` against the working file directly, as it may differ from what the view shows.

Calling `git diff` against the temporary `<file1>` using the `--git-dir` and `--work-tree` arguments doesn't work reliably and would slow down the diff process, if the working tree was located on a remote machine.

GitSavvy as an example uses `git hash-object -w` to create dummy commits for the local file, but this creates dangling objects for each modification in the database and also may slow down diffing on remote drives. This is no option!

**Comment by zertrin** [comment]
Thanks for the detailed explanation! I'll live with it 😉
